source 'https://rubygems.org'

gem 'rails', '~> 3.2'
gem 'simple_form'
gem 'validates_email_format_of'
gem 'simplecov', :require => false, :group => :test
gem "susy", "~> 1.0.8"
gem "normalize-rails", "~> 2.0.1"
gem 'carrierwave'
gem 'cloudinary'

group :development do
  gem 'sqlite3'
end

group :test do
  gem 'minitest-reporters'
  gem 'simplecov', require: false
end

group :production do
  gem 'pg'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'compass-rails', '>= 1.0.3'
  gem 'compass', '>= 0.12.2'
	gem 'faker'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
